<?php


/**
 * This class adds structure of 'nightload' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Sep 26 07:07:40 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class NightloadTableMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.NightloadTableMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(NightloadTablePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(NightloadTablePeer::TABLE_NAME);
		$tMap->setPhpName('NightloadTable');
		$tMap->setClassname('NightloadTable');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11);

		$tMap->addColumn('USER', 'User', 'VARCHAR', true, 25);

		$tMap->addColumn('BEGIN', 'Begin', 'TIMESTAMP', true, null);

		$tMap->addColumn('FINISH', 'Finish', 'TIMESTAMP', true, null);

		$tMap->addColumn('STATE', 'State', 'VARCHAR', true, 15);

		$tMap->addColumn('URL', 'Url', 'LONGVARCHAR', true, null);

		$tMap->addColumn('PROTOCOL', 'Protocol', 'VARCHAR', false, 10);

		$tMap->addColumn('PATH', 'Path', 'LONGVARCHAR', true, null);

	} // doBuild()

} // NightloadTableMapBuilder
