<?php


/**
 * This class adds structure of 'permissions' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Sep 26 07:07:40 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PermissionsTableMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PermissionsTableMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PermissionsTablePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PermissionsTablePeer::TABLE_NAME);
		$tMap->setPhpName('PermissionsTable');
		$tMap->setClassname('PermissionsTable');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11);

		$tMap->addForeignKey('LINK_ID', 'LinkId', 'INTEGER', 'links', 'ID', true, 11);

		$tMap->addColumn('GID', 'Gid', 'VARCHAR', false, 15);

		$tMap->addColumn('MODE', 'Mode', 'CHAR', true, null);

		$tMap->addColumn('CHANGE_AT', 'ChangeAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('CHANGE_LOGIN', 'ChangeLogin', 'VARCHAR', true, 25);

	} // doBuild()

} // PermissionsTableMapBuilder
