<?php
// auto-generated by sfRoutingConfigHandler
// date: 2010/08/06 08:47:01
return array(
'openid_finishauth' => new sfRoute('/cliens/finish', array (
  'module' => 'cliens',
  'action' => 'finish',
), array (
), array (
)),
'openid_error' => new sfRoute('/cliens/openidError', array (
  'module' => 'cliens',
  'action' => 'openidError',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'cliens',
  'action' => 'index',
), array (
), array (
)),
'um' => new sfRoute('/user/:action', array (
  'module' => 'um',
), array (
), array (
)),
'gm' => new sfRoute('/group/:action', array (
  'module' => 'gm',
), array (
), array (
)),
'remove_user' => new sfRoute('/removeUser/:user', array (
  'module' => 'gm',
  'action' => 'removeUser',
), array (
), array (
)),
'showMy' => new sfRoute('/myuploads', array (
  'module' => 'upload',
  'action' => 'showMy',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
