<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/09/09 16:00:58
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    '.actions' => 
    array (
      'login_module' => 'cliens',
      'login_action' => 'login',
      'secure_module' => 'default',
      'secure_action' => 'secure',
    ),
  ),
);
