<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/08/06 08:47:01
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    '.actions' => 
    array (
      'login_module' => 'cliens',
      'login_action' => 'login',
      'secure_module' => 'default',
      'secure_action' => 'secure',
    ),
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'auth' => 
  array (
    'is_secure' => false,
  ),
  'logout' => 
  array (
    'is_secure' => true,
  ),
);
