<?php
/**
 * Skeleton subclass for performing query and update operations on the 'registrationRequests' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Sep 26 07:07:41 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RegistrationRequestsTablePeer extends BaseRegistrationRequestsTablePeer
{
}
