<?php
// auto-generated by sfRoutingConfigHandler
// date: 2010/09/18 18:18:56
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'admin',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
