<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/18 18:18:56

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=upload;host=db.usic.lan',
  'username' => 'upload',
  'password' => 'ohGai4Ou',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),

'session' => new sfPDODatabase(array (
  'dsn' => 'mysql:host=db.usic.lan;dbname=sessions',
  'username' => 'session_user',
  'password' => 'aem4roGo',
  'name' => 'session',
)),);
