<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/09/18 18:19:59
sfConfig::add(array(
  'app_sf_phpopenid_plugin_lib_path' => '/home/caelum/public_html/project/lib/php-openid',
  'app_exceptionfilter' => true,
));
