<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/09/18 18:20:02
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    '.actions' => 
    array (
      'login_module' => 'cliens',
      'login_action' => 'login',
      'secure_module' => 'default',
      'secure_action' => 'secure',
    ),
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
  'download' => 
  array (
    'is_secure' => false,
  ),
);
